---
title: La domination du monde par l’intelligence artificielle, ça commence par la science

author:
  - name: Rosalie Gagnon
    email: rosalie.gagnon@usherbrooke.ca
    affiliation: Université de Sherbrooke
  
abstract: |
 Dans un monde ou la technologie avance à une vitesse lumière, un nouvel arrivant nous confronte. ChatGPT la nouvelle intelligence artificielle, fait des vagues. Versatile, il est garanti qu'il peut trouver une réponse à toutes vos questions les plus bizarres. Le monde de la science appréhende ce nouvel arrivant porteur d’un vent de fakes news. Utilisé à des fin malicieuses, ChatGPT pourrait être un désastre pour la communauté scientifique. Cependant, qui dit mauvais peut aussi dire bon. ChatGPT condamnera-t-il la science ou la fera-t-elle progresser comme jamais auparavant?
keywords: 
  - ChatGPT
  - Science

date: "`r Sys.Date()`"
classoption: preprint, 3p, authoryear
bibliography: mybibfile.bib #mettre le chemin du fichier source
linenumbers: false
numbersections: true
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
---

# **Introduction**
La science-fiction a, depuis bien longtemps, prédit l’avènement des intelligences artificielles. Qu’on prévoit la destruction du monde par celle-ci ou qu’on questionne la nature humaine même, l’intelligence artificielle est un miroir déformé de son créateur, l’humain. Si dans le célèbre roman ‘Les androïdes rêvent-ils de moutons électriques’ publié en 1968 par l’auteur Philip K. Dick, on ressasse une réalité futuristique ou l’on se questionne sur l’essence même de ce qui fait de nous des humain, la réalité du siècle est certainement différente. Aucune intelligente artificielle n’est encore assez développée pour qu’on se pose de tels questions. Cependant, avec l’apparition du nouveau chatbox appelé chatGPT des questions font surface. Qu’est-ce que cette intelligence peut causer comme impact sur la communauté scientifique? Un peu moins dramatiques que les questions existentielles proposées par ‘blade runner’, ce sont tout de même des questions qui nécessitent qu’on s’y penche. Si on lui demande, ChatGPT peut composer n’importe quel texte qui semble être écrit de la main humaine. Gagnant en popularité comme aucun autre site auparavant, il soulève avec lui, une vague de scientifique inquiets face aux impacts que peut provoquer cette nouvelle interface sur le monde de la science.



# **ChatGPT, un A.I versatile**
Mais qui est ce mystérieux A.I qui menace le monde de la science? ChatGPT est une intelligence artificielle présentée sous forme de chatbox. On peut lui demander n’importe quoi et il répondra de façon presque indiscernable à celle d’un humain. Que ce soit un poème, une liste d’épicerie, le rendement des cultures de soya en 2019 ou à quel moment de la journée tu devrais prendre tes vitamines, ChatGPT fournira une réponse. Hormis quelques garde-fous éthiques très vagues, Chat fourni presque en tout temps une réponse crédible et confiante. C’est là que réside une partie du problème. Selon un article publié dans le ‘American journal of bioethics’ le programme offre des réponses instantanées à des questions complexes sans autres alternatives à visiter au contraire d’un moteur de recherche comme google par exemple, qui lui fourni plusieurs liens à consulter.[@doshi_chatgpt_2023] Plusieurs utilisateurs du programme pourraient être amenés à croire tout ce qu’il leur est donné en réponse par celui-ci. De plus, son fin talent à reproduire ce qui semble avoir été écrit de toute pièces par un homme ou encore de réécrire un texte dans un différent style rend la détection du plagiat presque impossible. On craint ainsi qu’un flot de d’articles scientifiques générés par le chatbox se déverse sur le net, dupant la population avec sa crédibilité de fer [@noauthor_ai_nodate]. Sans être obligé de générer un article au complet, certains utilisateurs peuvent également utiliser ChatGPT pour un renseignement ou de l’aide dans leurs recherches. Ici, le danger est d’obtenir une réponse qu’on interprète mal ou qu’on ne comprend tout simplement pas et de l’utiliser dans un papier ou comme référence. Si on couple ce phénomène avec les sites de publication scientifique open access qui ne nécessitent pas de revues par les pairs avant la publication, nous avons alors à faire à un enfer de fausses informations à venir. 



# **Contrer les pouvoirs infinis de chatGPT par l’augmentation de la reproductibilité des études?**
Dans la communauté scientifique, on reconnait qu’il est presque impossible de reproduire exactement l’étude d’un autre scientifique en obtenant plus ou moins les mêmes résultats dans un intervalle de confiance raisonnable. Même les scientifiques qui tentent de reproduire leurs propres études peinent à arriver aux mêmes conclusions que précédemment. Selon un article de de Monya Baker publié en 2016, près de 60% des scientifiques en biologie on échoués à reproduire leurs propres études et 78% on échoués à reproduire celles d’un autre chercheur [@open_science_collaboration_estimating_2015]. Ce phénomène est dû en partie aux méthodes de travail utilisés. Pour avoir une étude reproductible, il est important de prendre en note chaque changement dans le code, chaque faux pas dans les manipulations, chaque modification de contexte d’interprétations des données dans le but ultime qu’un chemin clair et précis soit pointé. Ainsi ce chemin est facilement empruntable par d’autre scientifiques sans risque d’égarement ou de divergence ce qui mène optimalement à la même destination c’est-à-dire, les mêmes résultats et conclusions. C’est un détour que peu de scientifiques se donnent la peine de prendre puisqu’il demande en général plus de temps et d’argent que lorsqu’on utilise la méthode standard de noter seulement les grandes lignes d’une méthodologie. De plus, peu de scientifiques sont enclins à reproduire des études déjà faites puisque les papiers découlant de ces études sont infiniment moins enclins à se faire publier dans les revues ou les journaux. Cependant il serait avantageux pour la communauté scientifique d’adopter une éthique de travail qui facilite la reproductibilité puisque non seulement un bon pourcentage d’études publiés comprennent des erreurs et quelques fois de la falsification de données mais la reproductibilité pourrait servir comme un outil efficace contre l’engouement vers ChatGPT. Si notre chatbox national invente ses données et ses statistiques de toutes pièces basées sur n’importe quelles stupidités prises sur le net, la reproductibilité des études issues de celui-ce sera de zéro. Il sera ainsi plus facile de discerner un article honnête d’un article forgé par le bot. Il est donc avantageux pour tout le monde d’augmenter son taux de reproductibilité puisque les études en deviennent plus crédibles et on peut discerner les vraies des fausses. 



# **Dompter la bête et s’en servir à bon escient**
Mais, si chatGPt est si puissant, serait-il possible d’envisager une avenue où il pourrait être notre allié scientifique? Eh bien déjà plusieurs scientifiques s’en servent pour faire des revues d’articles, les aider à reformuler des paragraphes, ou autres petites tâches simplettes. Dans un article du journal Nature, une scientifique dit voir un avenir ou ChatGPT aide les scientifiques à devenir plus productifs au niveau de la recherche. ChatGPT a aussi été recconu pour son aide dans le domaine de la santé. Puisque le bot peut se concentrer sur l’analyse des données, les revues de littérature et autres tâches plus basiques, il laisse le temps aux chercheurs de se pencher sur la découverte et la compréhension de nouveaux médicaments [@sallam_chatgpt_2023] ce qui est une aide considérable. Mais allons voir plus loin pour un instant, serait-il possible qu’un jour, avec une stadardisation de la reproductibilité en science assez poussée et une éthique de travail impeccable ChatGPT puisse se pencher sur le travail faramineux de reproduire les études déjà produites? Ainsi, plus besoin de ‘perdre son temps’ à reproduire les études des autres. Les chercheurs peuvent se pencher sans cesses sur de nouveaux sujets pendant que la crédibilité de leurs papier publiés dans le passé sont vérifié par ChatGPT.  



# **Conclusion**

ChatGPT n’est sûrement pas la dernière intelligence artificielle que la science devra confronter. Autant des enjeux négatifs font surface comme le risque de plagiat, de falsification ou de publications de faux articles en masse sur le net, il y a aussi des avantages bénéfiques tel que l’aide à la recherche, à la synthèse de texte, à la revue de littérature ou à l’interprétation des données qui ont été mise de l’avant par ce nouveau programme. Finalement, il serait important de décréter une éthique de travail face à l’utilisation de ChatGPT en recherche scientifique avant de l’utiliser allègrement dans le domaine. Pour l’instant, il est important de faire preuve de transparence et d’augmenter son taux de reproductibilité le plus possible dans chaque recherche en attendant qu’une direction d’utilisation soit pointée. Qui sait, peut-être que, mis de paire avec une reproductibilité infaillible, chatGPT pourrait faire avancer la science comme jamais il à été vu auparavant, mais attendant nous devons être prudent avec ce nouvel outil à double tranchant. J'ai donc une opinion ni pour ni contre mais qui se veut vigilante en premier lieu mais ultimement je crois que Chat peut devenir un outil d'une grande utilité en science.



# References {-}



